### ISSUE TITLE
False "Invalid URL" message

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Shelf#15]
Happened when I tried to add link https://www.dcode.fr/exif-thumbnail
![bug](https://user-images.githubusercontent.com/581023/177872037-c05a8669-f936-475b-ad57-8bdb28af9cb9.jpg)

**Comment by pgpathan22** [comment]
Working for me in 2 devices. I have faced this once but then it is not there.

![Screenshot_1658231030](https://user-images.githubusercontent.com/74892023/179742822-89bd017b-81a8-4020-b78d-3ca4e8261aaa.png)

**Comment by kirillt** [comment]
If I understand correctly, the message happens sometimes. What we can do is to make error message more explicit/granular: in particular, there might be limit of redirects reached or something else. We should investigate which HTTP functions are used and which kinds of exceptions they can throw. After that we should catch them separately.
