### ISSUE TITLE
"Link to Web" resource kind

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Shelf#37]
It should be possible to work with URLs using the app.
This allows a user to use our app as bookmarks keeper.

1. Sharing a link from external apps must result in saving the link into one of user's folders.
2. Links should be represented as separate entities in resources grid and gallery view.
3. Opening any link must be possible with Firefox or Chrome.
4. Opening specific links should be possible with specialized apps (e.g. YouTube, MeetUp).

Open questions:
* Storage format. The easiest way is to save every URL into HTML file.
  Batching links into one file-database per root/favorite might be more efficient, especially for indexing.

* Reading of Firefox/Chrome export files (XML).
  Should we convert those files into our format or just adapt to them?

**Comment by mdrlzy** [comment]
We also need to figure out how to generate a preview for the link.
- The file name can be replaced with the page title.
- Parsing an image. For different sites, the methods will be different (e.g. YouTube, Instagram)

**Comment by kirillt** [comment]
@mdrlzy I would say preview should be part of the link's metadata.
Metadata can include page title and preview. We can allow a user to configure how much interactive they want preview to be.
E.g. in future, we can embed HTML browser into gallery mode and handle clicks etc.
For the beginning, preview should be just screenshot.

Actually, I think, bookmarks creation should be handled by separate micro-app.
Let's call it _ARK Bookmarks_. It should:

1. Allow to create new bookmark, manually or automatically from external apps via _share_.
    The link should be stored somewhere, where the user prefers, not necessary in a _root_.
    But in latter case, the user will be able to discover saved link in _ARK Navigator_.

2. Provide with metadata automatically by going by the link and extracting necessary data from the remote resource.

2. Allow to edit metadata. E.g. to replace automatically derived title with title chosen by the user.
    Similar to how we can edit images now, using external apps, we should be able to open a link (using pencil button) from _ARK Navigator_ into _ARK Bookmarks_.

**Comment by mdrlzy** [comment]
Link preview(title, description, image) can be obtained using [ogp](https://ogp.me/).

**Comment by kirillt** [comment]
Follow-up: https://github.com/ARK-Builders/ARK-Navigator/issues/235
